export const REQUEST_ACCOUNT_START = 'ethereum/REQUEST_ACCOUNT_START';

export const REQUEST_ACCOUNT_SUCCESS = 'ethereum/REQUEST_ACCOUNT_SUCCESS';

export const REQUEST_ACCOUNT_FAILED = 'ethereum/REQUEST_ACCOUNT_FAILED';
