name: deploy-client

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'client/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - run: aws s3 sync dist s3://contract-playground/client/latest/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
