name: deploy-client

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'client/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          REACT_APP_SERVER_URL: https://difchor7ka0de.cloudfront.net
          PUBLIC_URL: /client/latest/

      - run: aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET_NAME }}/client/latest/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/client/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1